using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using Godot;

namespace WorldMapStudio;

/// <summary>
/// Emits a TypeScript ambient declaration (<c>wms.d.ts</c>) describing the exact JS surface
/// <see cref="ScriptEngineHost"/> just bound, by walking the same <see cref="ScriptReflection"/>
/// metadata — see ScriptingDesign.md's "bindings and declarations are the same reflection pass"
/// principle. Written to a gitignored, repo-local <c>.types/</c> folder every startup (regenerated,
/// not hand-maintained, per ScriptingPlan.md decision #7).
/// </summary>
public static class ScriptTypeDeclarationWriter
{
    private static readonly Dictionary<Type, string> PrimitiveNames = new()
    {
        [typeof(void)] = "void",
        [typeof(string)] = "string",
        [typeof(bool)] = "boolean",
        [typeof(byte)] = "number",
        [typeof(short)] = "number",
        [typeof(int)] = "number",
        [typeof(long)] = "number",
        [typeof(float)] = "number",
        [typeof(double)] = "number",
    };

    /// <summary>Generates and writes <c>res://.types/wms.d.ts</c> from the given modules.</summary>
    public static void Write(IEnumerable<IScriptModule> modules)
    {
        string path = ProjectSettings.GlobalizePath("res://.types/wms.d.ts");
        string? directory = Path.GetDirectoryName(path);
        if (!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }

        File.WriteAllText(path, Generate(modules));
    }

    /// <summary>Builds the declaration text. Exposed separately from <see cref="Write"/> so it's testable without touching disk.</summary>
    public static string Generate(IEnumerable<IScriptModule> modules)
    {
        List<IScriptModule> moduleList = modules.OrderBy(m => m.Name, StringComparer.Ordinal).ToList();
        var visited = new HashSet<Type>();
        var worklist = new Queue<Type>();
        var sb = new StringBuilder();

        sb.AppendLine("// Auto-generated by WorldMapStudio's scripting system. Do not edit by hand —");
        sb.AppendLine("// it is rewritten every startup from the current [ScriptProperty]/[ScriptFunction] surface.");
        sb.AppendLine();
        sb.AppendLine("declare namespace wms {");
        foreach (IScriptModule module in moduleList)
        {
            Type type = module.GetType();
            Enqueue(type, visited, worklist);
            sb.AppendLine($"    const {module.Name}: {type.Name};");
        }
        sb.AppendLine("}");

        // Breadth-first over every type reachable from a module's properties/function signatures —
        // each type has exactly one entry in `visited`, so it is enqueued and therefore emitted once.
        while (worklist.Count > 0)
        {
            EmitInterface(sb, worklist.Dequeue(), visited, worklist);
        }

        return sb.ToString();
    }

    private static void EmitInterface(StringBuilder sb, Type type, HashSet<Type> visited, Queue<Type> worklist)
    {
        sb.AppendLine();
        sb.AppendLine($"interface {type.Name} {{");

        foreach (PropertyInfo property in ScriptReflection.Properties(type).OrderBy(p => p.Name, StringComparer.Ordinal))
        {
            sb.AppendLine($"    readonly {property.Name}: {TsType(property.PropertyType, visited, worklist)};");
        }

        foreach (MethodInfo method in ScriptReflection.Functions(type).OrderBy(m => m.Name, StringComparer.Ordinal))
        {
            string parameters = string.Join(", ", method.GetParameters().Select(p =>
                $"{p.Name}{(p.IsOptional ? "?" : "")}: {TsType(p.ParameterType, visited, worklist)}"));
            sb.AppendLine($"    {method.Name}({parameters}): {TsType(method.ReturnType, visited, worklist)};");
        }

        sb.AppendLine("}");
    }

    // Nullability is deliberately not modelled here (e.g. a method returning "Entity | null" is
    // emitted as just "Entity") — doing that precisely needs NullabilityInfoContext, which is more
    // machinery than this surface currently justifies. Known, accepted gap; see ScriptingPlan.md.
    private static string TsType(Type type, HashSet<Type> visited, Queue<Type> worklist)
    {
        if (PrimitiveNames.TryGetValue(type, out string? primitive))
        {
            return primitive;
        }

        if (type.IsArray)
        {
            return $"{TsType(type.GetElementType()!, visited, worklist)}[]";
        }

        if (type.IsGenericType && typeof(System.Collections.IEnumerable).IsAssignableFrom(type))
        {
            return $"{TsType(type.GetGenericArguments()[0], visited, worklist)}[]";
        }

        Enqueue(type, visited, worklist);
        return type.Name;
    }

    private static void Enqueue(Type type, HashSet<Type> visited, Queue<Type> worklist)
    {
        if (visited.Add(type))
        {
            worklist.Enqueue(type);
        }
    }
}
